name: Sample CICD
on: [workflow_dispatch]
jobs:
  Build:
    runs-on: self-hosted
    steps:
      - run: echo OK
  Test:
    runs-on: self-hosted
    needs: Build
    steps:
      - run: echo OK
  Dev_deploy:
    runs-on: self-hosted
    needs: Test
    steps:
      - run: echo OK
  Uat_Deploy:
    runs-on: self-hosted
    needs: Dev_deploy
    steps:
      - run: echo OK
  Prod_Deploy:
    runs-on: self-hosted
    needs: Uat_Deploy
    steps:
      - run: echo OK




